[package]
name = "chat_floem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "15.1.0"
floem = { path = "C:\\Rust\\libs\\floem" }